// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylayvgpstrbxsimkliza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsYXl2Z3BzdHJieHNpbWtsaXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDcyMzAsImV4cCI6MjA2NTk4MzIzMH0.94FE8yhMecS2pUIV5k0hR3B3X-3KeFzQvGUtUIdcIsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);